import numpy as np
# print(np.__version__)
# print(np.show_config())
vector = np.zeros(10)
# print(vector)
memory_size = vector.size * vector.itemsize
# print(memory_size)
# np.info(np.add)
arr = np.zeros(10)
arr[4] = 1
# print(arr)
vector_range = np.arange(10, 50)
# print(vector_range)
vector_0_9 = np.arange(10)
reversed_vector = vector_0_9[::-1]
# print(reversed_vector)
matrix_3x3 = np.arange(9).reshape(3, 3)
# print(matrix_3x3)
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indexes = np.nonzero(array)
# print(non_zero_indexes)
identity_matrix = np.eye(3)
# print(identity_matrix)
arr = np.random.random(3)
# print(arr)
arr = np.random.random(10)
# print(arr.max())
arr = np.random.random(10)
# print(arr.mean())
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
# print(matrix)
matrix = np.ones((3, 3))
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
# print(matrix)
# print(0 * np.nan)
# print(np.nan == np.nan)
# print(np.inf > np.nan)
# print(np.nan - np.nan)
# print(np.nan in set([np.nan]))
# print(0.3 == 3 * 0.1)
matrix = np.arange(9).reshape(3, 3)
# print(np.diag(matrix))
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)